### ISSUE TITLE
fails to mount tmpfs in jail

### ISSUE THREAD

**Issue by feld** [jrmarino/synth#10]
I have a jail where I have to build one port with custom options -- everything else can come from the FreeBSD pkg repository. Trying to use synth to build this port/package fails because it wants to kldload and mount tmpfs.

"synth configure" shows that tmpfs is not enabled for work area or /usr/local -- is tmpfs automatically used for /usr/obj ?

```
> # synth build irc/inspircd
> mount: tmpfs: Operation not permitted
> 
> raised REPLICANT.SCENARIO_UNEXPECTED : /sbin/mount -t tmpfs tmpfs /usr/obj/synth-live/SL09 => > failed with code 1
```

This is my very first time trying to use synth, so I might be doing something wrong :)

**Comment by jrmarino** [comment]
well the "something wrong" is running it in a jail. :)

But yes, there are several mounts of tmpfs that aren't configurable.  They are small and just use tmpfs unconditionally.  Only the two big boys, work around and localbase have options to dump to disk (which is a huge performance hit)

I'd recommend you run synth on a live system and re-enable tmpfs assuming the system has enough memory.  There's no point to using a jail, that's why synth is doing internally.

**Comment by jrmarino** [comment]
how's it going?  did you try running it outside of jail?
I just pushed a new version to ports.

**Comment by feld** [comment]
Hi, didn't try it yet but I think my attempt to use it within a jail was violating the original spirit of the tool. We can close this issue and I'll try it again soon outside the jail on that server :)

**Comment by jrmarino** [comment]
Dewayne Geraghty figure out how to make this work if you still prefer to run Synth in a jail:

https://github.com/jrmarino/synth#synth-fails-when-i-run-it-inside-a-jail--what-can-i-do

**Comment by omniuwo** [comment]
This could also mention that you may need to kldload tmpfs and/or nullfs on the host to be able to mount them inside the jail.

Also, if you have installed packages from outside the jail (like 'pkg -c /path/to/jail package') you need to bootstrap pkg inside the jail or synth build commands will give you the error "Unfortunately, the system upgrade failed. (system query)".

I ran it in a jail because I wanted to try it out in a throwaway environment and I'm excited, great stuff! =)
