### ISSUE TITLE
Upgrading from 11.0 to 11.1, "rebuild all 3rd party software"

### ISSUE THREAD

**Issue by roker** [jrmarino/synth#102]
Ok, normally this took hours but I am using synth since and the command "synth upgrade-system" seems the right one to execute, but it only rebuilded two ports and now I am not sure if I understood it correctly. Is this really a replacement for "portmaster -af" which would be run normally?? Sorry for asking, I am  searching for conformation as I somehow cant believe that few hours (or days) process was replaced with few minutes O.o

Thank you in advance (and maybe add few lines into documentation about upgrading the freebsd).

**Comment by jrmarino** [comment]
Well, it's okay for freebsd 11.0 to 11.1.
If it had been freebsd 11.0 to freebsd 12.0, it would have rebuilt everything because the ABI would have mismatched and caused all packages to be pre-deleted.
In the past, moving from 11.0 to 11.1 might have seen system libraries with major version updates (e.g. libxxx.so.3 => libxxx.so.4) but these days with symbolic versioning, the libraries don't get bumped anymore.

I think you're okay (assuming your ports tree was up to date before running the command)

**Comment by roker** [comment]
Ok, thank you very much :)
