### ISSUE TITLE
Exclude certain ports

### ISSUE THREAD

**Issue by melak** [jrmarino/synth#111]
Maybe this should be in #53 (or maybe this exists somewhere I can't spot). It would be nice to have a way to exclude packages (have synth not consider them) from building, kind of what `PM_EXCL` (`-x`) in portmaster-speak is.

My particular use case is that I generally run upgrades very frequently, but some things that take a long time to build I have explicitly excluded and only lift the exclusion once in a blue moon (but it also helps with misbehaving ports - qpdfview, for example, hasn't been building in a good while, so why even try).

**Comment by jrmarino** [comment]
that workflow isn't compatible with how synth works.
If synth wants to rebuild a dependency, you *must* rebuild it.  It's not doing it for fun.  Something in the current package is obsolete and the package has to be regenerated.

that type of usage is exactly why portmaster users find themselves with malfunctioning or unbuildable ports that aren't seen by other users, btw.  

I'd suggest let frequent builds.  In other words, don't build daily but try weekly (in sync with freebsd official builds to try to keep ports and packages compatible).  If you try building daily, you're definitely going to hit that "What!  I just built libreoffice and webkit-gtk YESTERDAY" ... pretty much every day.  It's a function of how ports are updated all the time rather than publishing an integral tree on a periodic basis.

**Comment by melak** [comment]
Ack, many thanks for clarifying!
