### ISSUE TITLE
speeding up reading the entire ports tree, and some more questions

### ISSUE THREAD

**Issue by ivr588** [jrmarino/synth#119]
Hi,
I have a synth instance running on a freebsd-11 amd64 bhyve guest, crossbuilding for arm6. It was started around midnight. About 10hrs later, it's at about 50%. The synth guest is with 4 cpus and 16GB ram.  The host system is Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (40 cpus and 128GB RAM). The guest is on a SSD. The host runs freebsd-12-amd64.

1. is there anything I can do to speed up reading the ports tree? I started it like this:
env SYNTHPROFILE=ArmBuild PKG_DBDIR="${SYSROOT}/var/db/pkg" synth build screen mutt bash

2. is reading the ports tree like this done every time synth runs?

3. does it need to be done every time my ports tree (in the freebsd-11 environment) is updated?

4. what happens if the timing of the ports tree update overlaps with the time synth reads the tree?

5. if I were to oversubscribe the number of workers and the number of jobs per worker (ie 10 jobs 20 workers when cpu=4), would synth crash?

6. can multiple synth instances be run (say one for armv6 and another for aarch64) be run at the same time?

7. Notes say that aarch64 can be compiled natively on freebsd-amd64. Is there a how-to/guide anywhere that shows how?

many thanks

**Comment by jrmarino** [comment]
The ports tree read occurs after the ports tree changes.  Many people have portsnap run on a cron job say every 24 hours and then have synth generate the index after so that it's already done when it's needed.

see forum starting from : https://forums.freebsd.org/threads/synth-version-2-00-flavor-support.63525/page-3#post-369174

Don't let the tree change under synth, EVER.  Have a second instance that won't change if necessary.

> if I were to oversubscribe the number of workers and the number of jobs per worker (ie 10 jobs 20 workers when cpu=4), would synth crash?

You'll most likely run out of swap space and freebsd is very unstable in that case.  Panics and freezes are likely.

> can multiple synth instances be run (say one for armv6 and another for aarch64) be run at the same time?
Only if you separate them using jails.  

> Notes say that aarch64 can be compiled natively on freebsd-amd64. Is there a how-to/guide anywhere that shows how?
The gcc7-aux for aarch64 stopped building because the headers for aarch64 changed mid-release.  The fix was easy; remove the header corrections from the bootstrap compiler.   I don't know if anybody actually fixed it.  If they did, synth would be one of the pre-compiled aarch64 packages.

**Comment by jrmarino** [comment]
yes, synth works on an ARM64 host natively.  Check to see if synth is in the latest arm64 packages.  If it is not, then nobody fixed the bootstrap headers yet.   You should be able to cross-compile as well, but I don't know the magic formula (if you figure it out, you can ask for a FAQ update)

**Comment by ivr588** [comment]
Have I got target and target_arch pointing to the right thinks?

many thanks,

**Comment by jrmarino** [comment]
I don't know, I don't cross-compile myself.  You could always send an email to jonathan chen and ask him politely for advice.

**Comment by ivr588** [comment]
OK, many thanks for your help
