### ISSUE TITLE
Build repository for another release?

### ISSUE THREAD

**Issue by Peter2121** [jrmarino/synth#143]
I cannot find any information about using synth for building a repository for another release of FreeBSD.
For example, I would like to build a repository for 11.1, using 11.2 server. Or even better - use 12.0 server to create a repository for 11.2 systems.
As I understand, using synth in jail is not recommended. So probably one should use another approach?

**Comment by jrmarino** [comment]
if you want something like freebsd 11.1 using a 11.2 server, you must use a jail for that use case.

In general, using a jail for synth has no benefit.   Some people insist on using synth within a jail, so that's fine.  It's just not necessary, unless you have a requirement like yours above where you need to build for older releases.

There's an entry in the FAQ for how to set up a jail to allow synth to work inside of it.
