### ISSUE TITLE
Lots of packages now getting: "failed dependency check."

### ISSUE THREAD

**Issue by GitHubinat0r** [jrmarino/synth#153]
This issue is similar to #108 

I'm having a number of packages fail the dependency check and fail to be added to the repository. Below is an example with postfix-current. I commented out everything in make.conf to reduce the chance of that having any impact. I'm having this issue across systems and ports on FreeBSD 12.0-RELEASE-p3.

I've also learned that the upgrade functionality is dangerious in this scenario. I had one system lose a lot of installed ports. Ports will install fine if I don't rebuild the repository and install the port manually using pkg.

synth just-build mail/postfix-current && synth rebuild-repository
                                                                         
The task is complete.  Final tally:
Initial queue size: 1
    packages built: 1
           ignored: 0
           skipped: 0
            failed: 0 

Duration: 00:02:03
The build logs can be found at: /var/log/synth
Stand by, prescanning existing packages.
Stand by, recursively scanning 184 ports serially.
Scanning existing packages.
postfix-current-3.4.20190106,5.txz failed dependency check.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt

at the end of /var/log/synth/mail___postfix.log:

--------------------------------------------------------------------------------
--  Phase: package
--------------------------------------------------------------------------------
===>  Building package for postfix-3.3.3_1,1
actual-package-depends: dependency on /usr/lib/libkrb5.so not registered (normal if it belongs to base)
file sizes/checksums   [151]: .. done
packing files          [151]: .. done
packing directories     [19]: . done

--------------------------------------------------
--  Termination
--------------------------------------------------
Finished: Saturday, 30 MAR 2019 at 02:15:40 UTC
Duration: 00:01:59

**Comment by Teetoow** [comment]
I still encountered similar problems when I tried to update some packages with "synth just-build".
When I recreated the repository it deleted lots of packages due to dependencies errors...
How could we update some packages without breaking other packages dependencies ??? 
Is it a bug or I missed something?

**Comment by jrmarino** [comment]
If I had to guess, you've got the "pre-fetch suitable packages" option selected and there was a mismatch between the available packages and the downloaded metadata.

Also, the "synth upgrade" command is dangerous in that build failures can cause issues when the pkg upgrade command is used.  That's why I don't recommend it and recommend that local repositories are built and verified before *manual" running of "pkg upgrade" commands.

so nobody else is reporting an issue, so I'd start with a build list (as a file) and use that list to rebuild a local repository.  It's not a systematic issue, it's something limited to your setup.

**Comment by GitHubinat0r** [comment]
Synth configuration profile: LiveSystem
===============================================================================
   [A] Ports directory            /usr/ports
   [B] Packages directory         /var/synth/live_packages
   [C] Distfiles directory        /usr/ports/distfiles
   [D] Port options directory     /var/db/ports
   [E] Build logs directory       /var/log/synth
   [F] Build base directory       /usr/obj/synth-live
   [G] System root directory      /
   [H] Compiler cache directory   disabled
   [I] Num. concurrent builders   2
   [J] Max. jobs per builder      2
   [K] Use tmpfs for work area    false
   [L] Use tmpfs for localbase    false
   [M] Display using ncurses      true
   [N] Fetch prebuilt packages    false

   [>]   Switch/create profiles
   [RET] Exit


/usr/local/etc/pkg/repos/FreeBSD.conf:
FreeBSD: {
        enabled: no
}

I've also done the build list as a file and a build list as a single port (like my example above) on multiple installs and have the same effect.

@Teetoow's comments also indicated one of the symptoms I noted in my first post. But you are correct, it could very well be configuration related as I'm the one managing these systems.

**Comment by Teetoow** [comment]
> so nobody else is reporting an issue, so I'd start with a build list (as a file) and use that list to rebuild a local repository. It's not a systematic issue, it's something limited to your setup.

I'm not sure to understand what you meant. Do you mean that it's not possible to keep dependencies for all packages already built when ports have been updated and some packages have been requested to be rebuilt?
Thus there is no equivalent to portmaster <installed package> which keep valid *all* packages available in the repository?

**Comment by jrmarino** [comment]
all packages that are out of date are rebuilt.
When the repository is generated, all the out-of-date packages are deleted during the process.

**Comment by jrmarino** [comment]
@Teetoow I think you're having conceptual issues.  it sounds like synth is working correctly for you.
If you update the ports tree every day and run synth every day, it's going to rebuild hundreds of ports, every day.  That's just the nature of it.  Poudriere is the same.

**Comment by Teetoow** [comment]
@jrmarino several hours ago, I just updated my ports because of python 3.7 bug.. I performed synth just-build python37.
After that I performed synth rebuild-repository to recreate my repository and update the new python package on my machines. However this command deleted (without my acknowledgment) hundread of packages because a library (provided by python3.7 which was rebuilt because of a new port version) broke other packages dependencies (and these packages were not rebuilt..).
I don't know if it's clear. I just swapped from portmaster to synth...

**Comment by jrmarino** [comment]
Well, sounds perfectly normal.
The rebuild-repository deletes obsolete packages.  With the python37 update, everything that depended on previously version of python37 was instantly obsoleted.
When you provide synth the build list (the top level ports you want the repository to have) everything will be rebuilt with integrity.  It's how it works (and poudriere is almost identical in this behavior).

**Comment by Teetoow** [comment]
Ok I'm sorry I missed that part of how it works. But my other question: how to specify to synth to **only** build a specific package with its dependances (and all packages which depend on them) with the build list?
My problem is: I don't want to rebuild all the packages of the repository each time a package has a security issue fixed...

**Comment by jrmarino** [comment]
you can't.  it rebuilds everything that requires rebuilding by design.  Choosing to intentionally break library linkages is not supported by synth.  A single port can cause a massive rebuild and you can't tell synth "I want you to do the wrong thing here".
(A response along the lines of "portmaster allows that" won't cause a blink.   This is considered the wrong action by both synth and poudriere.)

**Comment by GitHubinat0r** [comment]
Can you tell me why newly compiled ports would fail to be added to the repository? I was able to limit the cause to my original post above.

The below options (or no options set at all) will enable the package to be added to the repository without an issue. But as soon as I change the below to include OPTIONS_FILE_SET+=SASLKMIT (or simply include it in the make.conf), the above error of: 'postfix-current-3.4.20190106,5.txz failed dependency check.' ocurrs and the package is removed. The port will install fine if I don't rebuild-repository and install the port manually. 

Is this a port issue or synth related? Do you have any recommendations for checks I could do to narrow it down?

# This file is auto-generated by 'make config'.
# Options for postfix-current-3.4.20190106,5
_OPTIONS_READ=postfix-current-3.4.20190106,5
_FILE_COMPLETE_OPTIONS_LIST=BDB BLACKLISTD CDB DOCS EAI INST_BASE LDAP LDAP_SASL LMDB MYSQL NIS PCRE PGSQL SASL SQLITE TEST TLS SASLKRB5 SASLKMIT
OPTIONS_FILE_UNSET+=BDB
OPTIONS_FILE_UNSET+=BLACKLISTD
OPTIONS_FILE_UNSET+=CDB
OPTIONS_FILE_UNSET+=DOCS
OPTIONS_FILE_SET+=EAI
OPTIONS_FILE_UNSET+=INST_BASE
OPTIONS_FILE_UNSET+=LDAP
OPTIONS_FILE_UNSET+=LDAP_SASL
OPTIONS_FILE_UNSET+=LMDB
OPTIONS_FILE_UNSET+=MYSQL
OPTIONS_FILE_UNSET+=NIS
OPTIONS_FILE_SET+=PCRE
OPTIONS_FILE_SET+=PGSQL
OPTIONS_FILE_SET+=SASL
OPTIONS_FILE_UNSET+=SQLITE
OPTIONS_FILE_UNSET+=TEST
OPTIONS_FILE_SET+=TLS
OPTIONS_FILE_UNSET+=SASLKRB5
OPTIONS_FILE_UNSET+=SASLKMIT

**Comment by jrmarino** [comment]
I guess I don't understand the confusion here.
See : https://www.freshports.org/mail/postfix/
particularly: 
```
SASLKMIT=off: If your SASL req. MIT Kerberos5, select this
```
in makefile
```
SASLKMIT_LIB_DEPENDS=   libkrb5.so:security/krb5
```

By adding that line to the make.conf, you changed the dependencies of postfix.  Of course it will be obsoleted due to missing dependencies.   What I don't get is why this is unexpected by you.

**Comment by GitHubinat0r** [comment]
I don't believe there is any confusion here. (Keep in mind, you're in two different discussion threads for the same issue #.) I completely understand how that would invalidate a port and require a rebuild.

My issue is I can run 'synth just-build mail/postfix-current' endlessly because it will always fail the dependency check, but this only occurs only when I have SASLKMIT set. 

If you're able to compile this and run 'synth rebuild-repository' without it being flagged as missing dependencies, I apologize profusely as the issue is obviously mine.

**Comment by jrmarino** [comment]
It's because there's a bug in the postfix makefile.  (At least I consider it a bug, others may disagree).
The specification is "librkb5.so".  libkrb5.so is already on the base system, so this line "SASLKMIT_LIB_DEPENDS=   libkrb5.so:security/krb5" has NO effect on any freebsd system.  So if the port maintainer wants to use krb5 from base always, this line needs to be removed.  If he wants to use librk5 from the port, then the specification needs to be changed to libkrb5.so.X so that the dependency gets pulled in.

So the issue is synth is expected security/krb5 to be on the postfix dependency list, but the ports tree skips it because it finds it in base.  It's a common mistake port maintainers make.  They don't even realize it most of the time.

**Comment by jrmarino** [comment]
in other words, for you to fix it, either correct the SASLKMIT_LIB_DEPENDS line dependency, or comment the line out completely (if the base krb5 is fine).

**Comment by GitHubinat0r** [comment]
Thank you for the detailed explanation. 

I’ll ping the port maintainer and lookout for these errors in the future.

Thanks again!

**Comment by Teetoow** [comment]
I'm so sorry about disturbing your discussion but I didn't found another way to contact you... If you have a mail address or something like that, i would appreciate to write to you there.

Moreover I think my english is so bad that you missunderstood what I said. Thus I will try to reexplain what happened two days ago. 

Python3.7 had a security issue. Thus I updated ports and perform:
   `# synth just-build lang/python37`
This action recreated 4 ou 5 packages which are needed by python and have been upgraded in ports.
This is the normal action and I'm totally agree with that.

However when I rebuilt the repository with:
   `# synth rebuild-repository`
It wrotes hundred of lines like this:
   `&lt;package name&gt;.txz failed dependency check.`
and just deleted them from my repository (around 150 packages!!)
(I'm sorry I forgot to save the output of this command thus I lost most of these messages..)

Before updating ports and rebuilding python3.7 the "rebuild-repository" had no errors like that. Thus my conclusion is that the rebuild of python (and the 4 other packages which were rebuild at the same time..) broke dependencies of these 150 other packages.. In that case, why synth did not rebuilt them?

> you can't. it rebuilds everything that requires rebuilding by design. Choosing to intentionally break library linkages is not supported by synth. A single port can cause a massive rebuild and you can't tell synth "I want you to do the wrong thing here".

I'm totally agree with you and this is the way I want synth to work.

**Comment by jrmarino** [comment]
your english is fine, and I didn't misunderstand.
Let me try to explain.
The "rebuild-repository" command is manually issued when the administrator has successfully built all the required packages.  As part of the command, obsolete packages are removed.

So in your case, you didn't build your complete set of packages (which are determined by either having a text file with top level ports listed, or generating that list internally from synth upgrade-system).  So you issued the "rebuild-repository" command prematurely.  It correctly removed the obsolete packages but there weren't any valid packages there, so the new repository is much smaller than the first.

The "fix" is to tell synth to build an exact set of top-level ports (e.g. libreoffice, emacs, etc), and once that is complete, issue the "rebuild-repository" command again.  That will get in you the proper configuration wrt to your local repository.

**Comment by Teetoow** [comment]
Ok I got what you said. Unfortunately I guess there is no solution for what I want...

I need to upgrade ports when there is a security fix for a specific package but it also upgrade many other ports.. There is no problem for me if it upgrades the port and its dependencies.
I would like synth to also rebuild (or upgrade) other packages which depends on the rebuilt one.
But if I specify a list of top packages to synth it will upgrade ALL of them right? Even those who are not dependent of any package who have been rebuilt (the initial package and its dependences)...

Maybe with an example it will be easier to understand. 
Lets assume I have (and want to keep!) 5 packages in my repository: A, B, C, D, E
"A" has a security issue thus I want to upgrade it. I upgrade my ports. But modifications have been done on the five ports.
"A" depends on "B" thus synth will upgrade both packages, OK.
However "C" also depends on "B".. If "B" is upgraded and not "C" it breaks the dependance and "C" will be removed and I don't want that.
If I specify a file with the name of the five packages, synth will upgrade all of them.. But I don't want "D" and "E" to be upgraded! They doesn't depend on "A" nor "B" nor "C", even if there ports have been updated, I don't want them to be rebuilt nor upgraded.
In the present case I would like to find the solution in order to synth rebuild "A", "B" and "C" only.

Thus what could be the solution?

**Comment by GitHubinat0r** [comment]
I’m not the developer, but the only solution I can think of is synth on a virtual machine (or jail) per main port. Not really efficient, but that would address your use case.

**Comment by Teetoow** [comment]
> I’m not the developer, but the only solution I can think of is synth on a virtual machine (or jail) per main port. Not really efficient, but that would address your use case.

Thank you for your answer. Unfortunately, that's not realistic.. I have around 80 main ports. Splitting them would mean having multiple version of the same softwares and libraries (one per virtual machine...) that's unmaintainable for me :(

**Comment by jrmarino** [comment]
@Teetoow 
I don't really see how your example is valid.
To refine it, say you have a build list of A,B,C,D,E
You don't tell synth to build A and B.  You tell synth to build the entire list.
If the existing packages are valid (dependencies match) then it only builds what it needs to (in other words, it ignores the build command on those).
In any case, after the build command, the repository is complete.  It might have obsolete packages in the repository directory, but when you issue the "rebuild repository" command, it removes them.

So I think you've got a misunderstanding of how to maintain repositories maybe?  Because your example is of somebody doing it incorrectly.  Done correctly, the repository is always complete.

**Comment by Teetoow** [comment]
In fact I don't want to recompile ALL packages just because one of them has security issue fixed..
I receive something like 1 ou 2 security issues per week. I don't want to recompile 400 packages twice a week just for that (it costs too much time, energy, money and is absolutly useless for my purpose..).. Moreover I don't want to use the latest version (except when there is a security issue) for each software.. It might create too much work (check that the new version of every package does not break configuration file, work as before etc.)..
Rebuilding everything could be a good thing for some uses but not for all..
With portmaster it knows the wanted top packages (`pkg query -e '%a = 0' %o`),  I ask it to rebuild one package, it rebuild it, its dependencies and all packages which are dependent of them depending on the wanted packages. And that's it. 

I would really appreciate to have the same thing with synth. Let's imagine:
`# synth build package --keep-packages listOfAllWantedPackages.txt`
and synth could perform the exact same thing.
In my previous example:
`# synth build A --keep-packages listOfAllWantedPackages.txt`
And listOfAllWantedPackages.txt contains "A, B, C, D, E"
And this command will only rebuild A, B and C.

This technique also well maintains the repository.

**Comment by jrmarino** [comment]
it's not ALL.  It's ALL that require it.
The request is for all, but again, any request against a valid package is ignored.

**Comment by Teetoow** [comment]
> it's not ALL. It's ALL that require it.
> The request is for all, but again, any request against a valid package is ignored.

For sure but when I upgrade ports in order to get a security issue fixed, it also update many many other ports... and I don't care about these updates!

**Comment by jrmarino** [comment]
we're going in circles.   You don't get an option to do the wrong thing (partial builds).  Either you build everything required or nothing at all.   It's the nature of the beast.   It's also the same as poudriere.  Only portmaster lets you shoot yourself in the foot.  poudriere and synth will not.

**Comment by jrmarino** [comment]
Note that the freebsd ports tree is presented a unit.  It doesn't support having versions that aren't presented together.

**Comment by Teetoow** [comment]
Indeed I will stop my question after that and come back to portmaster which works perfectly since many years without absolutely any problem for me. The only bad thing is that it doesn't share packages like synth and poudriere do.

Three days ago python37 received a patch for a security issue, I wanted it. portsnap updated around 500 ports at the same time.
As an example one of them was postfix which absolutely does not depend on python nor any of its dependancies which were rebuilt. Postfix is one of the package I maintain. So you are explaining to me that it's crazy to not rebuild postfix because its port has been updated?
In that particular case, I'm obliged to compile each new port each time they are updated..

Why is it so evil to stay at a specific version of a specific package while there is no security issue and there is no need of a newer version for dependency question? If the answer is "there is no problem you can" why I would loose time and energy to compile newer version of it for.. nothing because I won't update it yet?

I'm not FreeBSD repository which try to have its package repository synchronized with their ports.. I'm just a very little administrator of two servers who don't want to build the same software on two different machine and prefer to compile it once and share the result. I though it was the purpose of synth..
I don't understand what's going wrong in my manner of administrating my machines.

**Comment by jrmarino** [comment]
2 thoughts: 
1) 400 packages is actually not impressive.   A decent machine should be able to rebuild 400 ports in 2 hours.   If twice a week is too much electricity, then update once a week or twice a month.
2) I don't get any bonus for users.  I'm no longer developing synth.  I only do support fixes (usually when freebsd ports developers change something drastic).  My new project is www.ravenports.com . so if portmaster does it for you, that's great.
