### ISSUE TITLE
Problem or confusion with "would you like to rebuild the repository"?

### ISSUE THREAD

**Issue by rwv37** [jrmarino/synth#181]
I recently opened [this thread](https://forums.freebsd.org/threads/synth-rebuild-repository-question.78719/) on the FreeBSD forums asking about the expected behavior of answering "yes" when `synth build` asks you if you would like to rebuild the repository. Please see that thread (including replies) for details, but long story short: Answering "Yes, I would like to rebuild the repository" does _not_ cause the same things to happen as would later doing a `synth rebuild-repository`.

It was suggested there that I open an issue here. It's not clear to me if it is supposed to be this way or not, and if it is supposed to be this way, then I don't understand what the point of answering "yes" is (or even the point of the question being asked in the first place).

**Comment by jrmarino** [comment]
well, I didn't read the thread but I'll try to answer anyway. 
If I recall correctly (It's been years since the code was written), the difference you are talking about involves validity checking.  If you answer "yes" after a focused build (anything that is not "everything" is focused), then validity checking is only performed on ports evaluated to accomplish the requested build.  So if you answer "yes" to rebuilding the repository, validity checking is partial -- it only covered the last build.  Therefore when you answer "yes", a repository is built on the existing packages -- no packages are deleted.  It is quite possible (even likely) the repository will have integrity issues -- referring to packages that no longer exist.

when you run the separate "rebuild repository" command, it does validity checking on all packages and will delete those with missing dependencies.  It can delete many (hundreds of packages).

Should there be two ways to do this?  I think you can successfully argue that the question you reference should be removed because it's dangerous for non-experts.

If you have a standardize port build file with all the top level ports you want, then answering "yes" to this question is fine.  The results should actualy match the separate rebuild command.  In all other cases, I'd recommend you answer "no" and always rebuild the repository with a separate command to ensure the resulting repository has integrity.

Does that help?

**Comment by jrmarino** [comment]
If I remember correctly, the question was added because people kept building one or two ports and when they ran the "build repository" command it deleted hundreds of ports and they were angry because they didn't understand why.

**Comment by rwv37** [comment]
> If you have a standardize port build file with all the top level ports you want, then answering "yes" to this question is fine. The results should actualy match the separate rebuild command.

Unless I'm misunderstanding what you're saying, I do have a standardized port build file with all the top level ports I want, but the results do not always match the separate rebuild command. Running `pkg upgrade -r Synth` will sometimes have different results based upon whether you've done one or the other.

In case I'm misunderstanding what you're saying: By "I do have a standardized port build file with all the top level ports I want", I mean that when I run `synth status` or `synth build`, I actually do `synth status topLevelPorts.txt` or `synth build topLevelPorts.txt`, with that file containing the list of the top level ports I want, one per line, e.g.:

> archivers/par2cmdline-tbb
archivers/p7zip
archivers/zip
databases/mariadb104-server
devel/ccache

... and so forth.

**Comment by jrmarino** [comment]
so do you build anything other than what's in the topLevelPorts.txt?
Ports add and remove dependencies all the time, so even with a standardized, you can see those kind of differences.

I think my recommendation in your case is aways answer "no" and rebuild the repository separately after building your standardized list.  You can't go wrong with that combination

**Comment by rwv37** [comment]
>so do you build anything other than what's in the topLevelPorts.txt?

I feel like I might be misunderstanding this question. Yes, when I do a `synth build topLevelPorts.txt`, it's not just the things that are directly listed in topLevelPorts.txt that get built. It also builds the things they depend on and so forth. As I understand it, that's the point of `synth build topLevelPorts.txt`, no?

**Comment by rwv37** [comment]
To be clear, I'm not asking "How do I get this to work". I understand that I can get it to work simply by doing a `synth rebuild-repository` in between the `synth build` and the `pkg upgrade`. What I don't understand is what the point of the question is in the first place, if you have to do that `synth rebuild-repository` no matter whether you answer yes or no.

**Comment by jrmarino** [comment]
you misunderstood the question.  It's not important, but I was basically asking if there were ports you built in addition to what was on the list and their dependencies -- e.g. running synth but providing individual ports on the command line.

I already answered about the genesis.  Basically it builds a repository without checking if the packages are valid.  It's not a good idea.  It came about because people got angry that 100s of builds they just built got deleted and they thought it was an error because portmaster didn't do that (but poudriere did).

I believe there's a version of the build command that doesn't ask this question as well.
It wasn't meant that you run "synth rebuild-repository" no matter what.
Again, if you're point that this question is a bad idea, I might agree with you.

**Comment by rwv37** [comment]
>you misunderstood the question. It's not important, but I was basically asking if there were ports you built in addition to what was on the list and their dependencies -- e.g. running synth but providing individual ports on the command line.

I do not do this.

>I already answered about the genesis.

I understand it was put in because people complained. What I don't understand is what it's supposed to actually accomplish (and therefore why it was put in at all rather than resolving the complaints by just not removing the old versions) given that you seem to need to do the separate rebuild regardless of whether you answer yes or no.

>It wasn't meant that you run "synth rebuild-repository" no matter what.

Doing this has worked 100% of the time for me, over many months, often several times a week. Not doing it (before I eventually figured out that doing it puts an end to the problems) worked sporadically at best. In what situation would anyone ever want to answer yes, but not go on to do a separate rebuild later anyway, before the `pkg upgrade`?

>Again, if your point that this question is a bad idea, I might agree with you.

If the answer is "There is no situation in which someone would ever want to answer yes, but not go on to do a separate rebuild later anyway, before the `pkg upgrade`", then yes, I think this question is a bad idea. It led to quite some time, when I first started using synth, where in some cases synth simply would not upgrade my system entirely, for reasons that were at the time incomprehensible to me, until I figured out myself that I had to do a rebuild regardless of whether I previously told it yes, rebuild. 

I even asked on this forum about the symptoms that were happening to me, and nobody said "Oh, saying 'yes, rebuild' is not enough; you also have to later say 'rebuild'".

**Comment by jrmarino** [comment]
So I went and read the man page to refresh my memory.
If one uses `synth just-build` instead of `synth build` then you avoid this issue completely.  

The nuances of "build-yes" weren't known at the time.  As you said, it often worked.  The users trained by portmaster could not understand why seemingly unrelated build tasks would wipe out half their recently built packages.

Short of removing `synth build` completely as an option, all I can recommend is to never use `synth build`, always use `synth just-build` instead.

All your points are valid.  Nobody considered that it was necessary to follow build-yes with a separate build command which is obviously undesireable.

**Comment by rwv37** [comment]
OK, great, thanks. Just to make sure I'm understanding, this is how I plan to update from now on (assuming nothing that comes from any of the steps indicates that I should proceed differently):

1. portsnap fetch update
2. pkg updating | more
3. synth status topLevelPackages.txt
4. synth just-build topLevelPackages.txt
5. synth rebuild-repository
6. pkg upgrade -r Synth
7. pkg autoremove

These are the same steps I've been taking for months now, except "just-build" instead of "build". Am I correct in thinking that this should be fine?

Thanks again.

**Comment by jrmarino** [comment]
Yes, that's looks good to me.
