### ISSUE TITLE
feature-request: `synth upgrade-jail`

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#21]
I don't know if this is possible but it would be nice to have a `synth upgrade-jail`command.
It could retrieve the jail's packages, rebuild what is necessary and upgrade the jail using `pkg -j`.

**Comment by jrmarino** [comment]
the request makes zero sense.
poudriere has "jails", synth does not.
there are no packages inside a synth builder.
The request basically makes no technical sense at all.  (not to mention it goes completely against the design target of Synth)

**Comment by bax-** [comment]
I think I didn't explain this properly:
The command would be used to upgrade jails that run under the host system.
If I have a jail called "mail" I can issue `pkg -j mail upgrade`or `pkg -j mail install postfix-current`or even `pkg -j mail upgrade -f -r Synth` (if Synth's repository is null-mounted into the jail).
Maybe Synth could upgrade jails the way it upgrades the host system.
Just an idea…

**Comment by jrmarino** [comment]
That's out of scope.  Synth's job is to create local repositories and as a special feature, interface with host system pkg(8) to update that system with a single command.  Beyond that, the user would have to manually update clients of the repository.

I would think the sysadmin would want to do this manually anyway.

**Comment by jrmarino** [comment]
Since synth is scriptable, I suggest the solution is to write a script to update the jails and command synth as necessary.

The main problem with scripting Synth though is failure due to obsolete port options.  Whenever a port option changes Synth is just going to stop and ask the user to fix it first.

I know I'll never add a command for this use case (particularly since there are other solutions) so best just to close it now.

**Comment by bax-** [comment]
👍🏻
