### ISSUE TITLE
graphics/drm-kmod fails to build

### ISSUE THREAD

**Issue by daemonblade** [jrmarino/synth#215]
graphics/drm-kmod currently fails to build. This is a meta-port that loads other kmods. The log complains:
...
pkg-static: POST-INSTALL script failed
`-- Installing gpu-firmware-radeon-kmod-turks-20220511...
`-- Extracting gpu-firmware-radeon-kmod-turks-20220511: ....... done
kldxref: can't create //boot/lhint.4EzBVx: Read-only file system
pkg-static: POST-INSTALL script failed
`-- Installing gpu-firmware-radeon-kmod-verde-20220511...
`-- Extracting gpu-firmware-radeon-kmod-verde-20220511: .......... done
kldxref: can't create //boot/lhint.Vhzctd: Read-only file system
pkg-static: POST-INSTALL script failed
Extracting gpu-firmware-kmod-20230210_1,1: ... done
===>   drm-kmod-20220907_1 depends on package: gpu-firmware-kmod>=20220511 - found
===>   Returning to build of drm-kmod-20220907_1
===>   drm-kmod-20220907_1 depends on file: /boot/modules/drm.ko - not found
===>   Installing existing package /packages/All/drm-510-kmod-5.10.163_2.pkg
Installing drm-510-kmod-5.10.163_2...
Extracting drm-510-kmod-5.10.163_2: ........
pkg-static: Fail to create temporary file for /boot/modules/ttm.ko:No space left on device
Extracting drm-510-kmod-5.10.163_2... done

Possible solution is to convert the chrooted /boot into a copy of /boot instead of a nullfs mount?

**Comment by jrmarino** [comment]
so this is only a problem with "synth test" right?
The post-install script wouldn't run if the package is just getting built.

or is it getting installed as a dependency of another port, perhaps?

**Comment by jrmarino** [comment]
right, the metapkg is failing because of this.

**Comment by jrmarino** [comment]
I'm not sure what the best solution is at the moment.  it's kind of tricky to make /boot read/write, and kind of heavy to duplicate boot for every builder construction.

**Comment by daemonblade** [comment]
Hmm. Can we get by with an empty (writable) /boot? Does the chroot'd sysroot require any reference to /boot? Do any ports make use of files under /boot?

**Comment by rtdean** [comment]
So I looked at the current builder mounts.  It looks like you are nullfs mounting `/boot` ro+noatime, and then mounting tmpfs for `/boot/firmware` and `/boot/modules`.  Could you instead (or additionally) unionfs a tmpfs over all of `/boot` (with noatime as well), so that the writes go to the tmpfs and you don't need to clone the objects in `/boot`?

**Comment by jrmarino** [comment]
I don't have good experience with fuse-based file systems.
Are the modules in /boot even used by FreeBSD ports?
If not, a writeable tmpfs could be inserted at /boot.

Installing outside of the PREFIX/LOCALBASE is the source of the problem but I guess that's where pkg is going now.

**Comment by chris3torek** [comment]
The `//boot/lhint.4EzBVx: Read-only file system` error is a bug in kldxref, fixed in FreeBSD HEAD but not in various releases (yet?). It tries to create a temporary new `/boot/modules/loader.hints` file and puts it in `/boot` instead of `/boot/modules`. It's best to just backport the fix from https://cgit.freebsd.org/src/commit/?id=f4613af424cc93d42f35730fd9862f0c6f964cbd and re-install kldxref.

Once that's done, the remaining problem is that the tmpfs file systems are now too small for some of the new modules. I raised the sizes from 100 MB to 1000 MB for both /boot/modules and /boot/firmware here. If you want I can make a fork of the repo and make an actual pull request but the change is really obvious...

```


commit 3726fd7bcab7efcc42438d725249999020626a4a (HEAD -> main)
Author: Chris Torek <chris.torek@gmail.com>
Date:   Tue Nov 19 01:51:50 2024 -0800

    ports-mgmt/synth: increase tmpfs sizes
    
    The loadable module and firmware builds are much larger now.
    Raise their tmpfs sizes from 100 MB to 1000 MB.

diff --git a/ports-mgmt/synth/files/patch-replicant.adb b/ports-mgmt/synth/files/patch-replicant.adb
new file mode 100644
index 000000000000..14f3d2b5b929
--- /dev/null
+++ b/ports-mgmt/synth/files/patch-replicant.adb
@@ -0,0 +1,11 @@
+--- src/replicant.adb.orig     2024-11-19 01:43:16.581345000 -0800
++++ src/replicant.adb  2024-11-19 01:43:41.546836000 -0800
+@@ -1170,6 +1170,6 @@
+                   mount_nullfs (target      => bootdir,
+                                 mount_point => location (slave_base, boot));
+-                  mount_tmpfs (slave_base & root_boot_fw, 100);
+-                  mount_tmpfs (slave_base & root_kmodules, 100);
++                  mount_tmpfs (slave_base & root_boot_fw, 1000);
++                  mount_tmpfs (slave_base & root_kmodules, 1000);
+                end if;
+             end;
```

**Comment by jrmarino** [comment]
did you want to open a PR?  if not, I can do it.

**Comment by jrmarino** [comment]
ah, you already covered that.  I'll do it.

**Comment by jrmarino** [comment]
new release with this change:
https://github.com/jrmarino/synth/releases/tag/v3.03
