### ISSUE TITLE
feature request: prune default make configs

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#28]
`synth prune-options` to delete make configs that aren't different to the defaults.
(to improve fetching prebuilt-packages and keep the options clean)

**Comment by jrmarino** [comment]
It can't prune the configs (the mount is read-only) but it could provide a list.
When an environment variable set, it could flag any configs that are the same as the default (and thus could be deleted).

Is that sufficient?

**Comment by jrmarino** [comment]
I mean flag during any ports scan, not a special command, and only when the env var is set.

**Comment by jrmarino** [comment]
actually, synth can't even easily do that.  It doesn't know what the default options are supposed to be because the presence of the saved configuration changes the results.

Maybe a separate script utility could be provided (assuming I can figure out how to get the default values by ignoring any saved options firstd).  So it wouldn't be part of synth, just a script utility people could run (likely only once or infrequently)

**Comment by jrmarino** [comment]
i could even write a shell script and port it directly to ports (e.g. /usr/ports/Tools/scripts/ ) as a general tool that lists options files that are identical to defauls.

That could work, right?  You could just pipe the stdout into xargs rm -rf to remove in one step.

**Comment by bax-** [comment]
That sounds great actually!

**Comment by jrmarino** [comment]
okay, done:
https://svnweb.freebsd.org/ports?view=revision&revision=408849

pull the latest ports and you can use it now.

**Comment by bax-** [comment]
great, thanks!
