### ISSUE TITLE
feature request: clean old packages

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#29]
could synth have a mechanism to delete either old, not needed or simply all built packages?

**Comment by jrmarino** [comment]
- It does delete old (obsolete) packages already (silently, during repo building)
- to delete all: rm -rf <location of packages>/*
- it can't know what is needed or not needed.  What's the problem here? If a valid package isn't installed, it's just taking up space in the repo but that's hardly a big deal.

I don't think there's anything to change here.

**Comment by bax-** [comment]
accepted
