### ISSUE TITLE
Another bug with using alternative base version

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#31]
Seeing another bug during the building of some ports using 10.2 world, but on 11-CURRENT host.

Specifically, first is the Platform: line still shows 11.0-CURRENTXXXXXX, shouldn't it show 10.2-XXXXXX? (Not sure if this is apart of the bug)

...
Platform: 11.0-CURRENTJAN2016 FreeBSD 11.0-CURRENTJAN2016 #3 1b5aa1f(HEAD): Tue Jan 12 21:19:28 UTC 2016     root@bellicose:/usr/obj/usr/src/sys/GENERIC  amd64
 ...

Next, during the configure phase, when it checks machdep, it returns freebsd11 still:

...
checking MACHDEP... freebsd11
...

This causes port such as lang/python27 to fail, since it puts some modules in a freebsd11 subdir, instead of freebsd10 where they are supposed to be. 

Full log file:
http://slexy.org/view/s2ANluwqlz

**Comment by jrmarino** [comment]
i'm not sure this is actually a "bug" per se.
the config script might be checking uname, which reads the running kernel.
In other words, it's running the chroot uname, but still getting 11 back because uname doesn't have a static value.

basically it's a case of python configure not accepting the --build target and trying to determine it on it's own.  other than patching the script, I'm not sure what the fix could be.

maybe it's time to research how uname actually works to see if it can be influenced.

**Comment by jrmarino** [comment]
it appears on uname can be influenced by environment variables:

```
#define	CHECK_ENV(opt,var)				\
do {							\
	if ((var = getenv("UNAME_" opt)) == NULL) {	\
		get_##var = native_##var;		\
	} else {					\
		get_##var = (get_t)NULL;		\
	}						\
} while (0)

static void
setup_get(void)
{
	CHECK_ENV("s", sysname);
	CHECK_ENV("n", hostname);
	CHECK_ENV("r", release);
	CHECK_ENV("v", version);
	CHECK_ENV("m", platform);
	CHECK_ENV("p", arch);
	CHECK_ENV("i", ident);
	CHECK_ENV("K", kernvers);
	CHECK_ENV("U", uservers);
}
```

**Comment by kmoore134** [comment]
Makes sense. Did a check and it looks like poudriere has to manually set a bunch of UNAME_* variables, probably to fix this exact issue.

kris@devastator:/usr/local/share/poudriere % grep UNAME *
jail.sh:        login_env=",UNAME_r=${release% *},UNAME_v=FreeBSD ${release},OSVERSION=${osversion}"
jail.sh:            login_env="${login_env},UNAME_m=${ARCH%.*},UNAME_p=${ARCH#*.}"

Is this something you want to fix / add? Otherwise in the meantime I'll have to hand-set those variables for builder environment.

**Comment by jrmarino** [comment]
i will have to fix it permanently and in the meantime you'll have to hand-set those variables.

**Comment by jrmarino** [comment]
Right now the <profile>-environment file cannot support any argument with spaces.  E.g. "MYVAR="a b" will _not_ work.

It's a limitation of the external library.  I might end up having to roll my own pipe handling rather than try to fix it (the library is bigger than I like and I don't use most of it anyway, but this is all post 1.00 stuff I think)

**Comment by kmoore134** [comment]
This appears to be fixed with the newer revision, not seeing ports fail to build due to base system / host system version mismatch now.

**Comment by jrmarino** [comment]
Yes, I rolled my own pipe command functions which gained the following:
1) it's no longer space sensitive.  Before 2 consecutive spaces in a command or env var string would break it.
2) it can accept quoted env variable values.
3) it can accept escaped spaces in lieu of quotes
4) it shrinks synth by 30%.
