### ISSUE TITLE
Feature Request: Method to sign the repo

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#39]
Looking for a way to digitally sign a repository, I.E. with pkg's built-in abilities.

Not sure which ways to do it, but maybe both with the RSA keys, and the "sign.sh" script itself may be nice. Personally just providing the path to sign.sh for synth would be fine for me.

(From the PKG man page)

     Create an RSA key pair:

           % openssl genrsa -out repo.key 2048
           % chmod 0400 repo.key
           % openssl rsa -in repo.key -out repo.pub -pubout

     Create a repository and sign it with a local RSA key.  The public key
     would be shared on all client servers with SIGNATURE_TYPE set to PUBKEY
     and its path set via PUBKEY setting in the repository configuration file:

           pkg repo /usr/ports/packages repo.key

     Create a repository and sign it with an external command.  The client
     should set, via the repository configuration file, SIGNATURE_TYPE to
     FINGERPRINTS and FINGERPRINTS to a path containing a file with the SHA256
     of the public key:

           # On signing server:
           % cat > sign.sh << EOF
           #!/bin/sh
           read -t 2 sum
           [ -z "$sum" ] && exit 1
           echo SIGNATURE
           echo -n $sum | /usr/bin/openssl dgst -sign repo.key -sha256 -binary
           echo
           echo CERT
           cat repo.pub
           echo END
           EOF

           # On package server:
           % pkg repo /usr/ports/packages signing_command: ssh signing-server sign.sh
           # Generate fingerprint for sharing with clients
           % sh -c '( echo "function: sha256"; echo "fingerprint: $(sha256 -q repo.pub)"; ) > fingerprint'
           # The 'fingerprint' file should be distributed to all clients.

           # On clients with FINGERPRINTS: /usr/local/etc/pkg/fingerprints/myrepo:
           $ mkdir -p /usr/local/etc/pkg/fingerprints/myrepo/trusted
           # Add 'fingerprint' into /usr/local/etc/pkg/fingerprints/myrepo/trusted

**Comment by jrmarino** [comment]
I'm thinking about a fixed path instead.  If both the private and public keys are present, the repo will be signed and 00_synth.conf will be configured to use the signed repository.

e.g. in /usr/local/etc/synth
[profile]-private.key
[profile]-public.key

Any script can generate the keys, but they would need to be copied/moved to /usr/local/etc/synth (perhaps private key needs to be 400 permissions otherwise synth stops and informs user that key isn't secure)

**Comment by jrmarino** [comment]
hmm, i guess there are two methods here: PUBKEY and FINGERPRINTS.
My first impulse is either support:
[profile]-private.key
[profile]-public.key
(PUBKEY method)
or:
[profile]-private.key
[profile]-fingerprints.key
(FINGERPRINTS)
depending on what the Synth user provides will determine how 00_synth.conf is built.

**Comment by jrmarino** [comment]
on second read, it looks like FINGERPRINTS don't take key file, but an external SSH signing command.  Not sure how to implement that yet.

**Comment by jrmarino** [comment]
maybe like this:
[profile]-signing_command
[profile]-fingerprints
I'd dump the contents of the first file and add it to the pkg command.  That should work.

**Comment by jrmarino** [comment]
Kris, I need some advice.
I implemented RSA keys entirely.  I can confirm (by exploding meta.txz) that the repository is getting signed.  I have 00_synth.conf getting created correctly. However, it doesn't actually *do* anything.

If I remove the public key lines from 00_synth.conf, it still installs packages from synth repository.  If I change the path to one that doesn't exist, everything is fine.   Does signed packages actually work?  How does one get pkg(8) to complain and not install anything because key configuration is mismatched?

I might just push the work because it's doing want pkg(8) man page say it should be configured and I don't think I did it wrong, but I don't see any difference actually using it.

(command server support isn't far off, it's already partially in place, but RSA keys is fully implemented)

**Comment by kmoore134** [comment]
Im heading to Japan but i will investigate when i get there. It sounds like a signed repo can be used in an unsecured manner without error. Did you try configuring your local repo using the fingerprints method? And if you change the public key does it then complain? 

--
Kris Moore

**Comment by jrmarino** [comment]
>  It sounds like a signed repo can be used in an unsecured manner without error.
or worse, it doesn't use the security at all.  I can't find any indication that a signiture is being checked.  Not on "pkg -vv", not on "pkg info <package>", nothing.  I'm starting to think RSA signatures are not actually supported

> Did you try configuring your local repo using the fingerprints method?
Fingerprints means signing server command and a fingerprints file.  As I mentioned earlier, the groundwork has been laid to support it, but doesn't take fingerprint files yet (it will not be difficult to add)  According to docs, RSA means path to public key and "signing_command" means fingerprint.  Maybe fingerprint for RSA method method works but it's not documented.

if you see bapt in japan, ask him. :)  and tell him to comment on this github issue.

**Comment by jrmarino** [comment]
So I've been playing with signing commands and fingerprints.  On my testing (outside of Synth) it's working.  However, I still can't break it!

e.g. I'll sign a repo with an command for an external signing server
then I'll generate the fingerprint

pkg works with:
A) no fingerprint setting
B) correct fingerprint settings
C) mismatching fingerprint settings

So no matter what I do, pkg NEVER complains.  And I get no indication whatsoever that a signature is being checked and matches.  I am very confused.

I am testing on DF by the way.  I doubt it would be different on FreeBSD but I guess it is possible

**Comment by jrmarino** [comment]
version 1.20 (available now) supports both methods (local RSA and signing command + fingerprints). The second method for sure works.  I am still skeptical about the local RSA keys though.

Please check it out and let me know.

**Comment by dmoutal** [comment]
Not sure if the packages are getting signed by the RSA key I generated as per the example in the man page but I get the following message when I rung `synth upgrade-system`:

```
The profile signing command was found but not the fingerprint
The generated repository will not be externally signed due to the misconfiguration.
```

Everything seems to bet working fine, but I looks like it is trying to fingerprint the repo despite the fact that I haven't set up fingerprinting (only RSA).

Here is my `00_synth.conf` file:
```
# Automatically generated.

Synth: {
  url      : file:///var/synth/live_packages,
  priority : 0,
  enabled  : yes,
  signature_type : PUBKEY,
  pubkey         : /usr/local/etc/synth/LiveSystem-public.key
}
```

I have disabled the FreeBSD repo by creating a `FreeBSD.conf` file with `FreeBSD: { enabled: no }` so I have no idea why it would be trying to fingerprint.

Hope this helps somewhat.

**Comment by jrmarino** [comment]
the 00_synth.conf is correct.
The error message might be bogus though.  I wasn't really done with testing (and hopefully the error message doesn't show if no LiveSystem-(signing files) are present at all.  I'll look.

**Comment by jrmarino** [comment]
okay, that warning should not show anymore with version 1.21, which is now available.

**Comment by jrmarino** [comment]
dmoutal, basically what happened is it was checking for fingerprints.  It should have returned false silently, but it returned false with a false warning.  It then checked the RSA keys, which it found, and signed the repository with them, and that's why you see the PUBKEY signature type on 00_synth.conf.

So your repository is signed (you can extract meta.txz to see signature file) and the repository conf file correctly points to the public key, but frankly I'm skeptical it works.  At least, I don't see any difference with or without the signature line, with or without the signed repository.  The only thing I may not have tried is corrupting the public key, and I'm guessing if I do that, nothing will change.

I highly suspect local RSA key signing is actually broken on pkg(8)

**Comment by jrmarino** [comment]
In case anyone is wondering, meta.txz tarball is different if signed by signing_command, so I don't think signing with local RSA key and then making a fingerprint of the public version of the RSA key will work either.  when signed by command, both the public key and signature is archived in meta.txz, but when signed by local key, only the signature is provided.

**Comment by dmoutal** [comment]
wow that was quick. Thanks!

And I can confirm I no longer the the fingerprint warning

**Comment by jrmarino** [comment]
Kris, have you had a chance to test this?
I was only able to get the commands to signing server method to work.

I need to get baptiste to look over RSA method to confirm if it's broken.

**Comment by kmoore134** [comment]
I've not had time to look at this, closing until somebody else does
