### ISSUE TITLE
Deadlock when unmount failed

### ISSUE THREAD

**Issue by kworr** [jrmarino/synth#4]
When synth unmounts it's env it should use umount -f to avoid situation where:

Me:

    du -hs /usr/obj

Kernel:

    Jan  9 17:30:39 probe kernel: unmount(/usr/obj/synth-live/SL09/xports): Cannot unmount: 3 mount refs still present
    Jan  9 17:30:41 probe kernel: unmount(/usr/obj/synth-live/SL09): Cannot unmount: 0 namecache references still present
    Jan  9 17:30:42 probe kernel: unmount(/usr/obj/synth-live/SL09): Cannot unmount: 2 mount refs still present

Mount:

    /pfs/@@-1:00009 on /usr/local (null, local)
    tmpfs on /usr/obj/synth-live/SL09 (tmpfs, local)
    /usr/dports on /usr/obj/synth-live/SL09/xports (null, local, read-only)

Synth:

    # ps axl | grep synth
    0  59518  30855  33 172   0  62560  45012 wait     I3L+    5    0:09,86 synth build sysutils/tmux
    0 378049  59518  30 170   0   3404   2076 pipewr   I0L+    5    0:00,02 /bin/rm -rf /usr/obj/synth-live/SL09

**Comment by jrmarino** [comment]
i've had bad experiences in the past with -f.
In this case, if an umount fails, it's always because a process is still running on it.  it's often better to just mount on top of it.

our poudriere actually will try umounting twice so that i cleans up mounts left over from previous runs that are now free to be unmounted (the process holding it exited).  It might be a good idea to attempt two unmounts if a mount is still detected (after a success umount).  I'll think about it.

This is kind of an unavoidable side effect of using chroot over a jail.  Some ports (generally freebsd ports that never successfully built during testing for dports) are just badly behaved or their processes lock up during building.

**Comment by kworr** [comment]
I see your point. Process groups and session ids can be used to monitor and kill groups of processes but they are not perfect. The only way to reliably find a hanging process is probably creating user-per-executor so all spawned process will still belong to that user and as can be killed at once with `su -m userx killall`.

**Comment by jrmarino** [comment]
I've got a hanging watchdog now and I did use process groups to implement it.
It should reduce the incidence of leftover mounts by a lot.
I'm going to push 0.98_3 soon which contains the fix.
