### ISSUE TITLE
synth removes mariadb server and client and installs mysql-client

### ISSUE THREAD

**Issue by pavalos** [jrmarino/synth#44]
I use mariadb instead of mysql, and synth wants replace it with mysql.

```
Installed packages to be REMOVED:
        mariadb100-client-10.0.23
        mariadb100-server-10.0.23

New packages to be INSTALLED:
        mysql56-client: 5.6.27 [Synth]
```

**Comment by jrmarino** [comment]
1) That's pkg(8), not synth
2) That's caused by you missing entries in make.conf

You have to set a variable for the "flavor" of mysql you want.  see Mk/bsd.databases.mk or something like that.

bottom line: it's a PORTS user error

**Comment by jrmarino** [comment]
note that you are probably missing the entry in /usr/local/etc/synth/LiveSystem-make.conf too

**Comment by jrmarino** [comment]
It's not clear why pkg(8) is doing this though.  Must be something bsd.databases.mk-specific

**Comment by pavalos** [comment]
I added DEFAULT_VERSIONS+=mysql=10.0m to make.conf, and it appears synth is behaving, so perhaps this indeed is a user error; however, portmaster -ad worked just fine, so that's why I thought it was a synth problem. Do you think it would be beneficial for synth to emulate portmaster's behavior?

**Comment by jrmarino** [comment]
No.  I can't find a way to say this without coming off rude, but the question is indicative of a lack of understanding about how Synth creates its sandbox.  (also why it does it this way and how many modes Synth is used, e.g. building for systems other than the localhost).  The other thing it implies is that portmaster is doing it correctly, which it is not.  If portmaster were conceptually correct, there would be no need for Synth to exist.

On the  flip side, the handing of MySQL, MariaDB, and perconaDB is pretty terrible, so that's partly to blame too.

sorry about the tone but I could just not think of a way to say it without sounding like an ass so I just said it anyway.

**Comment by pavalos** [comment]
You didn't hurt my feelings ;) I asked that precisely because I don't know that much about Synth and was just throwing out an idea. Thanks for the explanation, and thanks for creating this tool.

Closing this issue: PEBKAC.
