### ISSUE TITLE
Add mention of synth configure to "missing distfiles dir" message

### ISSUE THREAD

**Issue by tigersharke** [jrmarino/synth#54]
New jail, new install, chose to install synth via pkg to save time.  This is not something I setup frequently, so details can slip my mind.  After I knew I had a fresh ports tree via portsnap, and synth via pkg, I attempted to build my first port.  Synth gave me an error message about something I assumed was already setup but I followed the suggestion: created alternate distfiles directories and revised my /etc/make.conf file to reference it.  The next and additional attempts also failed, asumed permissions issues, wrong format of entry in make.conf file. I had forgotten about _synth.conf_ via **_synth configure_**, which was still set to look for **/usr/ports/distfiles** location.

Hmm.  Interesting.  It seems that after the initial synth configure creates the synth.conf file, it will test for a valid distfiles location.  The message I encountered might only be displayed in a very initial situation but it still may be useful to prompt to use or auto-initiate **_synth configure_**.

**Comment by jrmarino** [comment]
I don't really see any added value.
The obvious step of a "missing directories" message is to check the configuration, so telling somebody to do that doesn't add anything IMO.  Especially since that's just about the only command that works at that point after __synth version__ and __synth help__

Moreover, users that have non-default locations for ports, distfiles, etc., should pretty much be assuming that they have to configure in order to define those locations.  (and that's if they run synth without ever reading any documentation).

At some point I may write "real" instructions that would fit with a handbook (e.g. how to do x,y,z) and telling people to verify the configuration at the first usage will be in those instructions.
