### ISSUE TITLE
How to build a port with a header file as configuration?

### ISSUE THREAD

**Issue by raphaelahrens** [jrmarino/synth#56]
Hi,

I wanted to install the port x11/sterm, but it fails when I set the variable `ST_CONF` to some path in the `make.conf``.

The error I get is 

> cp: /path/to/file/config.h: No such file or directory

The file is there, and when I run `make -C /usr/ports/x11/sterm` it builds without an error.
(with `/etc/make.conf`` linked to `/usr/local/synth/LiveSystem-make.conf`)

So how can I build this port with my `config.h`?

**Comment by jrmarino** [comment]
This is a severe hack in the port.  The implication is that it not only can be built manually, but without a real builder such as poudriere and synth.

However, it might be possible if you put the conf file in a system directory such as:
/bin
/sbin
/usr/include
/usr/lib
/usr/share
/boot
the distfiles directory

then you can change make.conf to that location.

You can even put it in the ports directory, but you'd have to set the path to "/xports/<category>/<port>/<myconffile>" and it would be wiped out if you use portsnap eventually so that's not a great idea.

**Comment by jrmarino** [comment]
i don't recommend the distfiles directory, but if you use it, it path needs to be "/distfiles", not what it really is.

**Comment by raphaelahrens** [comment]
By putting the file into `/usr/share` I was able to build the port. Thanks.

And I have to agree that the port is not ideal. But the alternative would be a huge `make config` dialogue.
