### ISSUE TITLE
consider tweaking watchdog limits

### ISSUE THREAD

**Issue by jrmarino** [jrmarino/synth#57]
e.g. check-plist: from 3 => 10
build: from 20 => 25
stage: from 20 => 25

e.g. gcc, giant tex ports

**Comment by mpeterma** [comment]
Did you thought about having this limits dynamically calculated, ie. by taking account of some environmental conditions (CPU, IO bandwith)... just an idea - not sure if this can be realistically achieved.
In any case I'd find it useful to have the limits configuration exposed as environment settings / config in the synth.ini so that they can be tweaked without rebuilding synth.

Best regards,
Matthias

**Comment by jrmarino** [comment]
it already is.

**Comment by mpeterma** [comment]
ok, thanks
