### ISSUE TITLE
synth keeps building lang/llvm37

### ISSUE THREAD

**Issue by markand** [jrmarino/synth#68]
Hello,

Each time I try to build a port (example `synth install multimedia/mpv`), synth compiles lang/llvm37. The package is installed and has been built somewhat like 3 times. There is updates since I didn't update the ports tree.

I wonder if that's normal or a bug because it takes 3 hours to build for me so I would like to avoid rebuilding again and again.

**Comment by jrmarino** [comment]
> The package is installed
That is irrelevant.  Synth does not use installed packages to build new ones.

> I wonder if that's normal or a bug
It's not a bug.

There is a log starting with 06_* which explains why dependencies are rebuilt.  Right now ports is changing dramatically, every day, pretty much since 31 Dec 2016.  My guess is that these big changes are correctly causing rebuilds.  Synth works better if run weekly for this reason (Some people try to run it daily which is pretty much overkill and not efficient).  You didn't note the frequency of the rebuilds though.  llvm37 is forced to get rebuilt quite often and quite easily.

**Comment by markand** [comment]
> Right now ports is changing dramatically, every day, pretty much since 31 Dec 2016.

Yes, but I told that I didn't updated the ports tree at all since the initial checkout on 26 december 2016.

The 06_obsolete_packages.log contains this:

graphics/libEGL package depends on llvm37-3.7.1_4.txz which doesn't exist or has been scheduled for deletion

But I'm not sure if that one comes from my attempt to install multimedia/mpv. As a suggestion, we could add timestamps in that file? :)

**Comment by jrmarino** [comment]
the log is always the last run.  It's overwritten every time.  Timestamps are pointless in that case.

**Comment by jrmarino** [comment]
note that you can use "synth status multimedia/mpv" and see what will be rebuilt (and why) as a dry run.  It's just FYI though since it's not avoidable.
