### ISSUE TITLE
synth upgrade-system yields 'bad input for 'Value: ""'

### ISSUE THREAD

**Issue by Rolinh** [jrmarino/synth#7]
Running `synth upgrade-system` on a FreeBSD 10.1 host failed with the following trace:
```
Scanning entire ports tree.
 progress: 96.36%              
culprit: packages/portmaster-backup
Scan aborted for an unknown reason.
bad input for 'Value: ""
Failed to scan ports tree   (Synth must exit)
```

Prior to this failure, two ports were marked with "failed dependency check".

**Comment by jrmarino** [comment]
We saw this with DISTDIR, apparently packages get placed in /usr/ports/packages by default.

Until it's fixed in the codebase, you need to move /usr/ports/packages somewhere else (and maybe set PACKAGES in /etc/make.conf to point to them)

**Comment by jrmarino** [comment]
should be fixed by 61c235e

**Comment by bsdforge** [comment]
Hi John. I mentioned in the FreeBSD forums, that I ran into this same failure. I hadn't noticed mention of it here, because it's not listed as open. I'm running 0.98_2, and I seem to recall that you mentioned in the forums that use of /usr/ports/packages/* was acceptable. Or will I need to move my packages, and create a pointer in make.conf(5) ?

Thanks

**Comment by jrmarino** [comment]
Your version of synth is too old.  Version 0.98_4 has been out of a week and it fixed the problem here.  Upgrade to the latest available version and you'll be fine.

**Comment by bsdforge** [comment]
Just did. Thanks, John.
