### ISSUE TITLE
curses interface: "checksum" displayed instead of "fetch" 

### ISSUE THREAD

**Issue by asxbsd** [jrmarino/synth#73]
A very  minor thing:

Following a interrupted download, upon next synth restart the distfile is checksummed, and the download is started anew.

However, the displayed phase remain on "checksum" instead of "fetch".

(seen on games/flightgear-data)

**Comment by asxbsd** [comment]
forgot to add that I'm reporting this only because I suspect a mis-identified phase might affect the watchdog timeout.

**Comment by jrmarino** [comment]
It's not bug.
Checksum phase will fetch if necessary.  That's how ports defined it (so it's out of scope to argue it shouldn't be that way).  In your case it was necessary because the present distfile had a mismatch so the fetch was reattempted after deleting the distfile.

The watchdog has the same time limits for checksum as fetch for this reason, so it's not an issue.

**Comment by asxbsd** [comment]
OK, thanks for clarifying and glad to know it is not an issue, it was not immediately obvious to me.
