### ISSUE TITLE
New Feature Requirement: Only rebuild  ports which directly depend on the updated port

### ISSUE THREAD

**Issue by dengxf2008** [jrmarino/synth#83]
Hi jimarino,
    I have a feature requirement.
    when port AAA changed, those ports BBB depend on AAA will be rebuilt, and the rebuilt of ports BBB  will cause ports YYYs to be rebuilt, etc. and it take some long time.

so if the BBB has nothing updated, can the rebuit stop on BBB, that means **ONLY** rebuild the top level ports which depend on the updated ports.

Thank you very much.

**Comment by jrmarino** [comment]
your "requirement" is not technically feasible.  Port changes have further consequences than one level up and neglects run dependency requirements.  Put another way, Synth using the same build strategy as poudriere, the "official" build tool.  That strategy is used for reasons that would be lengthy to explain.

**Comment by dengxf2008** [comment]
I known the best way is rebuild all.
but in real world, for example: ONLY security/libressl updat from 2.5.3_1 to 2.5.4, in my system synth will rebuild > 500 ports, and when done. only libressl is updated to system. other ports which were rebuilt keep untouched due to no changes.

**Comment by dengxf2008** [comment]
I rebuild all every week, but wish only build the updated ports daily.
so give user the option as below may be better:
- rebuild all related
- rebuild only top level related
- rebuild only them itself, no related.

**Comment by jrmarino** [comment]
It's not possible to only rebuild libressl when there is a version change.  Every single package that requires libressl directly has to be repackaged because the version changed.  The package manifests single package versions to the revision number.

Your suggestion is obviously user-centric, but it's not based in sound technical feasibility.  The technique has to work in ALL cases, not one or two contrived ones.  If it fails in a single case, it's not usable.

**Comment by dengxf2008** [comment]
pkg upgrade command will only re-install the updated packages and part of the related packages depend on PORTVERSION and PORTREVISION, it always a small number.
the time of rebuild from source code maybe very long for desktop. and a minor PORTREVISION may cause hundreds of packages to recompile.
I think re-package is enough for some case after check PORTVERSION and PORTREVISION, and will decrease the time a lot.

**Comment by jrmarino** [comment]
This is a VERY old topic that has been discussed MANY times.
Everyone notices pkg(8) does not install everything that is built.
That doesn't mean that the building is redundant or unnecessary.  There is a LOT more to the analysis to try to minimize the building.  I've done the analysis.  I know of approaches that can cut building down a lot, but they are very complex.

Yes, a minor portrevision can cause hundreds, even thousands of packages to rebuild.  That's a known characteristic.  The same is true for poudriere.  With how ports is released (daily changes versus periodic publishing) that's just going to happen.

You could open an issue with poudriere identically to this one.  They are aware of the consequences of a single portrevision change as well, but it's "nature of the beast".

Yes, I know techniques to improve it, but it's not as simple as you suggest.  It involves completely manipulating the build order so that packages are temporarily allowed to be deleted and rebuilt without invalidating anything downstream that depends on this.  These recursive calculations are quite complex.
