### ISSUE TITLE
Can't build devel/gcc-arm-embedded

### ISSUE THREAD

**Issue by daemonblade** [jrmarino/synth#86]
A `synth build devel/gcc-arm-embedded` results in:
```
The task is complete.  Final tally:
Initial queue size: 1
    packages built: 1
           ignored: 0
           skipped: 0
            failed: 0

Duration: 01:56:14
The build logs can be found at: /var/log/synth
Stand by, recursively scanning 1 port serially.
Scanning existing packages.
gcc-arm-embedded-6.3.20170628.txz failed dependency check.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100%    260 B   0.3kB/s    00:01
Fetching packagesite.txz: 100%  195 KiB 199.5kB/s    00:01
Processing entries: 100%
Synth repository update completed. 809 packages processed.
All repositories are up to date.
pkg: No packages available to install matching 'devel/gcc-arm-embedded' have been found in the repositories
Unfortunately, the system upgraded failed.
```

Here are the contents of `/var/log/synth/06_obsolete_packages.log`:
```
devel/gcc-arm-embedded package has less dependencies than the port requires (9)
Query: textproc/expat2:expat-2.2.1
math/gmp:gmp-6.1.2
print/indexinfo:indexinfo-0.2.6
devel/isl:isl-0.18
math/mpc:mpc-1.0.3
math/mpfr:mpfr-3.1.5_1
lang/python2:python2-2_3
lang/python27:python27-2.7.13_6

gcc-arm-embedded-6.3.20170628.txz failed dependency check.
```

I don't know how to debug what is wrong with the `devel/gcc-arm-embedded` port, and why *synth* is remarking that the port is invalid.

**Comment by jrmarino** [comment]
In my opinion, devel/gcc-arm-embedded is affected a port bug, 
specially this line
```
LIB_DEPENDS= libelf.so:devel/libelf
```
The issue is that ports was specifically designed for a line like that.  Thus, the bug is in the *design* of dependencies.  This line actually means, "Search for libelf.so library.  If you don't find it, add devel/libelf to the dependency list".  What's happening is that libelf is being found, so it's not adding the package dependency manifest.

The proper method (in my opinion; I can insure others disagree) would be something like
```
.if !exist(/usr/lib/libelf.so)
LIB_DEPENDS= libelf.so.0:devel/libelf
.endif
```
(notice hardcoded soname)

So my stance on this is conditional dependencies should be removed from freebsd ports as its a terrible idea, but the fact is that the people who put it in *on purpose* thinks its clever.

If you want to fix it locally, your choice is either
   1. remove libelf.so:devel/libelf
   2. change libelf.so to libelf.so.0
   3. contact maintainer, explain the issue and see if he'll adjust port so that anybody with synth can build it.

Obviously option 3 is the best, but the maintainer will have to acknowledge that he cares about synth users and that he can maintain the port identically with a minimum tweak.  

He may not realize that on FreeBSD, the LIB_DEPENDS= libelf.so:devel/libelf line does **nothing** because all releases of FreeBSD have this library.  So the only effect of this line currently for freebsd users is to break synth.

**Comment by daemonblade** [comment]
Thanks for the analysis. I will raise a PR and see what the maintainer says.

**Comment by daemonblade** [comment]
Pending outcome of https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220782

**Comment by daemonblade** [comment]
PR committed and closed.

This issue has now been resolved.
