### ISSUE TITLE
Undocumented: Synth uses pkg instead of ports tree for dependency resolution?

### ISSUE THREAD

**Issue by zilti** [jrmarino/synth#92]
Apparently synth ignores the port configs for dependency resolution and solely uses pkg, is that correct?

I have a setup with apache24 and mariadb102-server which I can install and update with portmaster, but synth simply removes one of the two because they "conflict" according to pkg.

**Comment by jrmarino** [comment]
> Apparently synth ignores the port configs for dependency resolution and solely uses pkg, is that correct?

no, that is not correct.

As I have no information on
A) how you tell synth what to build
B) what are the contents of your <profile>-make.conf (or even if they exist)
.. I don't know what your issue is.  I can speculate that expectations formed by using portmaster in the past are responsible for misconceptions of how synth works.

**Comment by zilti** [comment]
Ok, scenario, I want to install the following ports:

- apache24
- otrs with the mysql option disabled
- mariadb102-server

- pkg install otrs: would install apache24, otrs and mysql56-server (obviously)
- portmaster / ports makefiles: would install apache24, otrs and mariadb102-server
- synth install otrs: would install apache24, otrs and mysql56-server.

Upgrading a system with apache24, otrs and mariadb102-server using synth upgrade-system silently uninstalls either mariadb or otrs and apache.

make.conf is empty except for MAKE_JOBS_NUMBER.

**Comment by jrmarino** [comment]
well, major issue #1 is that you expect /etc/make.conf is used.
It's not.  the "<profile>-make.conf" is used instead.
That distinct is listed in the synth man page as well as README of this github site.

as far as otrs goes, synth uses the options directory you specify in the configuration menu.  If you have ports in default locations, then it should pick up previously saved port options (you can check what directory is being used and ls the directory to see if OTRS has been configured).

But since you now mention mariadb, which is NOT a ports default, that means you're missing a MYSQL version definition in the <profile>-make.conf file that you apparently haven't configured yet.  (and the fact you didn't mention it on make.conf might mean you didn't configure it there either).

A quick ports lesson:
If you don't configure things explicitly, the default databases (perl, python, php, ruby, etc) are built into repositories.   If you build a repository with different defaults than you use locally, pkg(8) will install/deinstall as you describe.  

So it sounds like you skipped configuring the repository to defaults you want.  (which again, is done through the profile's make.conf, which is NOT /etc/make.conf)

**Comment by jrmarino** [comment]
Did that resolve the issue?  can we close the issue now?
