### ISSUE TITLE
USE_GCC=7 seems to be ignored

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#93]
```
# cat /usr/local/etc/synth/LiveSystem-make.conf 
DEVELOPER=yes
FFLAGS+= -O2 -pipe -march=bdver2 -mtune=bdver2
FFLAGS+= -funroll-loops --param max-unroll-times=4 -ftree-vectorize
FFLAGS+= -g
DEFAULT_VERSIONS=gcc=7
.if !empty(.CURDIR:M/usr/ports/net/mpich)
USE_GCC=7
.endif
```
However, when I force build net/mpich, I still get:
```
$ mpicc --version
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin
```
I think this is wrong.
When I use same options in /etc/make.conf and
build net/mpich directly, i.e. "make -C net/mpich" I get, as expected:
```
$ mpicc --version
gcc7 (FreeBSD Ports Collection) 7.2.0
```

**Comment by jrmarino** [comment]
You're putting a LOT of confidence in the correctness of LiveSystem-make.conf.
Unfortunately, you made mistakes with it.

(unrelated) mistake 1: do not define DEVELOPER.  You're interfering with synth, which sets DEVELOPER as needed.
mistake 2: line .if !empty(.CURDIR:M/usr/ports/net/mpich) is wrong.
synth does not put the ports tree at "/usr/ports".  You assume it does, but that's a bad assumption.
This this condition is never satisfied.  IIRC, it puts it at /xports.

As an aside, putting per-port modifications in *-make.conf isn't really clean.
You might consider putting "Makefile.local" or "Makefile.FreeBSD" in the ports tree (e.g. /usr/ports/net/mpich/Makefile.local) in order to keep the make.conf clean and global.

**Comment by jrmarino** [comment]
also, setting USE_GCC=7 for every port except for 1 is a terrible idea and will result in hundreds of build failures I suspect.

**Comment by mexas** [comment]
sorry to be an idiot. I used to know all this years ago.
Then I just used pkg defaults for several years and forgot.
Now I need to remember how to do custom builds.
Makefile.local worked fine.
Thanks!
